#!/bin/bash
sudo yum update
sudo easy_install pip
sudo pip install virtualenv
sudo cd /home/ec2-user
sudo virtualenv environment
sudo source environment/bin/activate
sudo pip install -r requirements.txt
